---
apiVersion: v1
kind: Secret
metadata:
  name: johne8-johne8-poi-backend-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/Summit23Janus2/johne8-backend-gitops
